### ISSUE TITLE
Failed to compile due to "kuberam-expath-plugin" execution

### ISSUE THREAD

**Issue by dovikos** [eXist-db/xquery-versioning-module#4]
### What is the problem
Failed to compile the project due to `kuberam-expath-plugin`.

### What did you expect
I expected the project to compile without failure, and finally get both `target/xquery-versioning-module-1.1.2.xar` and `target/xquery-versioning-module-1.1.2-exist.jar` (as explained [here](https://github.com/eXist-db/xquery-versioning-module/blob/master/README.md)).

### Describe how to reproduce or add a test
Compile the project as explained [here](https://github.com/eXist-db/xquery-versioning-module/blob/master/README.md) (with the Java 8 and Maven 3 requirement).
The build fails during `kuberam-expath-plugin` execution. It seems that path to the built `target/xquery-versioning-module-1.1.2-exist.jar` is incorrect
(`\\C\Users\[some path]\xquery-versioning-module\target\xquery-versioning-module-1.1.2.jar` insteaf of `C:\Users\[some path]\xquery-versioning-module\target\xquery-versioning-module-1.1.2.jar`).
Here is the stacktrace (I put in bold relevant informations to me):

<pre>[INFO] --- kuberam-expath-plugin:0.4.8:make-xar (create-xar) @ xquery-versioning-module ---
[INFO] descriptorsDirectoryPath: C:\Users\[some path]\xquery-versioning-module\target\expath-descriptors-7a87d469-cd5d-4b21-ae88-ca8f9de89d0a
mavenResourcesExecution: org.apache.maven.shared.filtering.MavenResourcesExecution@4a9860
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource to C:\Users\[some path]\xquery-versioning-module\target\make-xar-tmp
[INFO] Resolved artifact: org.exist-db.xquery.extensions:xquery-versioning-module:jar:1.1.2
<strong>java.io.FileNotFoundException: \\C\Users\[some path]\xquery-versioning-module\target\xquery-versioning-module-1.1.2.jar (Le chemin réseau n'a pas été trouvé)</strong>
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
	at java.net.JarURLConnection.getManifest(JarURLConnection.java:231)
	at java.net.JarURLConnection.getMainAttributes(JarURLConnection.java:283)
	at ro.kuberam.maven.plugins.expath.mojos.MakeXarMojo.getMainClass(MakeXarMojo.java:273)
	at ro.kuberam.maven.plugins.expath.mojos.MakeXarMojo.execute(MakeXarMojo.java:177)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.027 s
[INFO] Finished at: 2017-03-23T08:54:03+01:00
[INFO] Final Memory: 21M/231M
[INFO] ------------------------------------------------------------------------
[ERROR] <strong>Failed to execute goal ro.kuberam.maven.plugins:kuberam-expath-plugin:0.4.8:make-xar (create-xar) on project xquery-versioning-module</strong>: Execution create-xar of goal ro.kuberam.maven.plugins:kuberam-expath-plugin:0.4.8:make-xar failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal ro.kuberam.maven.plugins:kuberam-expath-plugin:0.4.8:make-xar (create-xar) on project xquery-versioning-module: Execution create-xar of goal ro.kuberam.maven.plugins:kuberam-expath-plugin:0.4.8:make-xar failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution create-xar of goal ro.kuberam.maven.plugins:kuberam-expath-plugin:0.4.8:make-xar failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at ro.kuberam.maven.plugins.expath.mojos.MakeXarMojo.getMainClass(MakeXarMojo.java:278)
	at ro.kuberam.maven.plugins.expath.mojos.MakeXarMojo.execute(MakeXarMojo.java:177)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more</pre>

Note that the project build succeeds if I remove the `kuberam-expath-plugin` from `pom.xml`: at least the `target/xquery-versioning-module-1.1.2-exist.jar` is built.

### Context information
- xquery-versioning-module version + Git Revision hash: 1.1.2 / 1c1bfba3b6a89760a1903b47236e0da4ec4847de
- Java version: Java8u121
- Operating system: Windows 7
- 64 bit
- No custom changes

**Comment by adamretter** [comment]
@dovikos As this works on my Mac here, I guess this is a Windows platform bug with the Kuberam EXPath plugin itself. As such could you instead open the issue with their project and link it from here: https://github.com/claudius108/kuberam-expath-plugin

**Comment by dovikos** [comment]
@adamretter You're right. Thanks for the answer.

**Comment by adamretter** [comment]
@dovikos Can you paste a link to the kuberam-expath-plugin issue into this issue please, so we don't loose track of it.

**Comment by claudius108** [comment]
I will take care of this.

**Comment by adamretter** [comment]
@claudius108 :-)
